/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package judge;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Avishek
 */
public class problemPage extends javax.swing.JFrame {

    /**
     * Creates new form problemReal
     */
    private int index ;
    private Connection conn = null ;
    private PreparedStatement pst = null ;
    private ResultSet rs = null ;
    private String username ;
    private int points ;
    public problemPage( int index , String s ) 
    {
        this.index = index ;
        this.username = s ;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        jLabel1.setText("Problem");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 270, 50);

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(10, 80, 310, 350);

        jLabel2.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        jLabel2.setText("TimeLimit :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(11, 460, 90, 17);

        jTextField2.setEditable(false);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(110, 460, 50, 20);

        jButton1.setFont(new java.awt.Font("Superclarendon", 1, 13)); // NOI18N
        jButton1.setText("Submit Solution");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(354, 370, 180, 29);

        jLabel3.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        jLabel3.setText("Points :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(27, 490, 60, 17);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(110, 490, 50, 26);

        jButton2.setFont(new java.awt.Font("Superclarendon", 1, 13)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(470, 0, 83, 29);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 50, 510, 30);

        jTextField4.setText(" ");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(390, 200, 150, 26);

        jButton3.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        jButton3.setText("Add Tag");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(400, 230, 107, 29);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/judge/Screen Shot 2016-09-26 at 19.08.03.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 570, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        editorPage j = new editorPage(); 
        //setVisible(false);
        int time = Integer.parseInt(jTextField2.getText());
        j.set(index , time ,username , points );
        j.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        //problems p = new problems();
        //p.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String tag = "# " + jTextField4.getText();
        try
        {
                   
        String sql = "Select * from problems where number='"+index+"' ";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        String temp = "";
        while(rs.next())
        {
            temp = rs.getString("tags");
        }
        if( temp == null )
            temp = tag ;
        else
            temp += (" " + tag );
        String sql1 = "Update data1.problems set tags = '"+temp+"' where number ='"+index+"'";
        conn.createStatement().execute(sql1);
        jLabel4.setText(jLabel4.getText()+tag);
        }
        catch(SQLException e)
        {
            System.out.println("Error while adding tag!!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    { 
        
    }
    public void set()
    {
        conn = MySqlConnect.connection();
        String sql = "Select * from problems where number="+index;
        try
        {   
            //pst.setString(1, "ADD");
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next())
            {
                String name = rs.getString("problem");
                String statement = rs.getString("statement");
                int timelimit = rs.getInt("timelimit");
                String tags = rs.getString("tags");
                points = rs.getInt("points");
                jLabel1.setText(name);
                jTextField1.setText(statement);
                jTextField2.setText(""+timelimit);
                jTextField3.setText(""+points);
                jLabel4.setText(tags);
            }
        }
        catch(SQLException e)
        {
            System.out.println("Failed to fetch Problem");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
